//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang_TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD
    {
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public string MaKH { get; set; }
        public System.DateTime NgayMua { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongThue { get; set; }
        public Nullable<decimal> TongGiam { get; set; }
        public Nullable<decimal> TienKhachDua { get; set; }
        public Nullable<decimal> TienThua { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
