//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang_TapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string TenDV { get; set; }
        public string TenLSP { get; set; }
        public int SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public decimal GiaNhap { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<double> KhuyetMai { get; set; }
        public Nullable<double> Thue { get; set; }
    }
}
